### ISSUE TITLE
Protobuf v5 support

### ISSUE THREAD

**Issue by Tradias** [sogou/srpc#406]
In order to update the protobuf port within vcpkg, srpc must support the new version. Can you add support for it?

Potential patch: https://github.com/microsoft/vcpkg/blob/052b06a95da4cee184bab4422e02e7f316055a99/ports/srpc/protobuf-v5.patch

**Comment by holmes1412** [comment]
Thank you for updating vcpkg for srpc! 

Now I notice the compatibility issues in protobuf 26.x. I read the document and have some questions, because I cannot find the new define in this document: https://protobuf.dev/reference/cpp/api-docs/google.protobuf.util.json_util/.

Is the `always_print_default_values` ​​mentioned in https://protobuf.dev/news/v26/ the same as `always_print_primitive_fields`?

**Comment by Tradias** [comment]
Interesting observation. I cannot find any mentioning of `always_print_default_values` in the code. I suspect it is a bug in the documentation.

Looking at the code they clearly changed `always_print_primitive_fields` to `always_print_fields_with_no_presence` from v25 to v26.

**Comment by holmes1412** [comment]
lol I see~ I will check the protobuf v26 and update srpc as your patch mentioned.

**Comment by holmes1412** [comment]
Hi, we have made this modification to support the new field. Please check this Pull Request https://github.com/sogou/srpc/issues/406 if you are interested.
